### ISSUE TITLE
Composer PHP version error

### ISSUE THREAD

**Issue by freddo256** [maxhoesel-ansible/ansible-collection-pterodactyl#132]
When trying to install pterodactyl panel using the information provided in README, I bumped into the following error:
```
Composer detected issues in your platform: Your Composer dependencies require a PHP version \">= 8.0.2\". You are running 7.4.3.
```

I am running this on an `ubuntu-20.04` container on Proxmox VE 7.4-3

My `main.yml`:
```
- name: Install Pterodactyl
  hosts: pdt-panel
  tasks:
  - name: Install Pterodactyl Panel
    include_role:
      name: maxhoesel.pterodactyl.pterodactyl_panel
    # pterodactyl_panel supports additional options, see it's README for more details.
    vars:
      pterodactyl_panel_app_key: <my app key>
      pterodactyl_panel_hashids_salt: <my app salt>
      pterodactyl_panel_timezone: Europe/Brussels
      pterodactyl_panel_db_host: "<mysql ip>"
      pterodactyl_panel_db_name: panel
      pterodactyl_panel_db_user: <mysql user>
      pterodactyl_panel_db_password: "<mysql password>"
      # Paths to the certificate. This defaults to the Let's Encrypt directory for your hosts domain name
      #pterodactyl_panel_ssl_cert: "/etc/letsencrypt/live/{{ ansible_fqdn }}/fullchain.pem"
      #pterodactyl_panel_ssl_key: "/etc/letsencrypt/live/{{ ansible_fqdn }}/privkey.pem"
      # Mail server settings.
      # pterodactyl_panel_mail_host: smtp.gmail.com
      # pterodactyl_panel_mail_user: your-address@gmail.com
      # pterodactyl_panel_mail_password: your-mail-password
      # pterodactyl_panel_mail_encryption: tls
      # By default, the role will create a user with the credentials admin/admin.
      # You can change these values below or in the UI once the panel is up and running
      pterodactyl_panel_admin_mail: "your-address@gmail.com"
      #pterodactyl_panel_admin_user: admin
      #pterodactyl_panel_admin_password: admin
```

Complete output: https://pastebin.com/b34x498Z
